name: payments

services:
  database:
    container_name: payments_db_main_postgres
    image: postgres:17.0
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"